### ISSUE TITLE
Possible memory leak with 2.4.0

### ISSUE THREAD

**Issue by mithrandyr** [rmbolger/Posh-ACME#47] opened 2018-06-15 20:06 UTC
When running `Set-PAServer LE_STAGE` the powershell process is consuming an inordinate amount of memory (until the process/ explorer crashes).

Attach is a screenshot showing at what point powershell.exe start to consume memory.  I've added the "-debug" switch to `Set-PAServer LE_STAGE' in order to track when the issue occurs.
                                                                            
![tempsnip](https://user-images.githubusercontent.com/16905470/41487178-9092d4b6-70b5-11e8-9344-74d255e3141c.png)

**PSVersion:** 5.1.17134.112
**PSEdition:** Desktop
**BuildVersion:** 10.0.17134.112
**CLRVersion:** 4.0.30319.42000
**OS BUild:** 17134.112

**Comment by mithrandyr** [comment] 2018-06-15 20:31
Ok, from further research I've identified the issue not so much with the POSH-Acme module, but rather with a conflict between this module an another module on my system.  I was able to narrow the conflict down to the presence of a "types.ps1xml" file.  If this type is loaded (via the PSD1 "TypesToProcess" configuration element) then the memory issue occurs, if the type is not loaded, then there are no problems.

**To Reproduce**
Use the attached file and run `Update-TypeData -AppendPath string64.Types.ps1xml`
(make sure to remove the ".txt" off the file first).
[string64.Types.ps1xml.txt](https://github.com/rmbolger/Posh-ACME/files/2107408/string64.Types.ps1xml.txt)

**Comment by rmbolger** [comment] 2018-06-16 15:55
This definitely reproduces on my system and I think I've managed to narrow it down to the bare minimum repro steps. Ultimately, it looks like the native `ConvertTo-Json` **really** doesn't like the extension methods for some reason.  Try this:

```powershell
$test = 'some string'

# before loading the extensions, no problem
$test | ConvertTo-Json

# load the extension
Update-TypeData -AppendPath .\string64.Types.ps1xml

# try again with the same variable, trigger memory leak
$test | ConvertTo-Json
```

Unfortunately, I don't think there's anything I can do to work around this. The JSON conversion functions are critical to this module's functionality.

**Comment by rmbolger** [comment] 2018-06-16 15:58
I just tested this on PowerShell Core 6.0.0 with the same results. And since that's open source, we might be able to track down the root cause and submit an issue.

**Comment by rmbolger** [comment] 2018-06-17 06:29
Submitted issue [#7091](https://github.com/PowerShell/PowerShell/issues/7091) on the PowerShell Core team's repo.

**Comment by rmbolger** [comment] 2018-06-18 18:39
Closing this as wontfix only because there's nothing I can really do about it. Even if the PowerShell team fixes the underlying issue, it's unlikely to get ported back to Windows PowerShell. So you'd be stuck having to run the latest PowerShell Core in order to make it work.

**Closed by rmbolger** 2018-06-18 18:39 UTC
Labels: wontfix
