### ISSUE TITLE
Implement retries for challenge validation before giving up

### ISSUE THREAD

**Issue by spaceygithub** [rmbolger/Posh-ACME#130] opened 2019-03-25 14:18 UTC
Hello Ryan
Would it be possible to add a retry function to the manual DNS plugin?
Many a time I've gone off an added the DNS entries, waited a while, done a few DNS lookups to check the population is complete but still get caught out by the validation failing against a DNS server I've not waited long enough for. It would be great if the routine asked if you wanted to try validation again, rather than just exiting. Rerunning generates a new string, so I have to change the DNS and wait again. 

Admit the real answer is for me to be more patient but I'm wondering if its a simple add for you?

Thanks in advance and thanks for the latest updates, I'm loving the new IAM Role support!!!
Gareth

**Comment by rmbolger** [comment] 2019-03-25 15:34
So back when the ACME spec was still in draft status, I could've sworn the server wouldn't allow you to retry which is why the module doesn't do it on its own already. But re-reading the recently finalized [spec](https://tools.ietf.org/html/rfc8555#section-8.2) makes it seem like you can actually request that the server retry validation without submitting a new order.

However, there's no easy way to make this happen on a per plugin basis since they're not involved with the challenge validation process, just the publishing of the challenges. But it's probably possible to add retry logic to the general challenge validation logic that would work for any plugin. I just have to think about the best way to handle that. This may also tie in with another feature I've been meaning to add for a while that does a pre-check on the records before asking the ACME server to validate.

In any case, no promises about a quick turnaround. But I'll leave this issue open to remind me.

**Comment by rmbolger** [comment] 2019-03-26 06:02
So I did some testing and verified that the current Let's Encrypt server implementation does not allow you to retry challenges. If any challenge fails and is marked "invalid", the whole order is then marked "invalid" and any subsequent requests to the challenge validation URL return an error like this:

> Unable to update challenge :: authorization must be pending

But this seems to contradict the current state of the spec. So I opened a thread on the community forums asking for clarification on the intended functionality. We'll see what they say. Here's a link if you want to keep track of the conversation.

[Regarding Retrying Challenges](https://community.letsencrypt.org/t/regarding-retrying-challenges/89606)

**Comment by rmbolger** [comment] 2019-03-26 15:10
It looks like the current functionality is working as intended by Let's Encrypt. The spec language uses "SHOULD" for whether the server allows retries and they've currently chosen not to support it. So unfortunately, there's nothing we can do from the client side to retry other than submit a new order and everything that goes along with it (new tokens for TXT records and such).

I'm gonna close this for now. But I'll keep it in the back of my mind if they ever change the implementation. I'm also still hoping to add some sort of client side pre-check that will augment or replace the existing DNSSleep parameter so that the client will simply wait (up to a timeout) until is has verified the TXT record exists before submitting the challenge for validation.

**Closed by rmbolger** 2019-03-26 15:10 UTC
Labels: enhancement
