### ISSUE TITLE
DNSPlugin for Cloudflare

### ISSUE THREAD

**Issue by rian-hout** [rmbolger/Posh-ACME#14] opened 2018-05-09 14:16 UTC
I wrote a DNSPlugin for Cloudflare.  I'm having trouble make a pull request to upload the file.  I'm receiving a permissions error.  Can you help with this?

**Comment by rmbolger** [comment] 2018-05-09 16:27
Did you fork this project into your own GitHub profile and make changes to the fork? Or did you just clone this project directly and make changes there?

If it was the latter, the problem is that you don't have access to push changes directly into this repository. Here's a decent guide on contributing to a project on GitHub.
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

If you're getting a permissions error uploading to your own fork, I have no clue what might be wrong. You might need to contact GitHub support.

**Comment by rian-hout** [comment] 2018-05-09 18:46
I just did a fork and created a pull request.

**Comment by rmbolger** [comment] 2018-05-12 01:29
This is now in the master branch and will be included in the next release.

**Closed by rmbolger** 2018-05-12 01:29 UTC
Labels: enhancement
