### ISSUE TITLE
String was not recognized as a valid DateTime on some non-US culture OSes

### ISSUE THREAD

**Issue by Genghes** [rmbolger/Posh-ACME#208] opened 2019-12-02 00:31 UTC
Hi. 
When running Submit-Renewal i get:
Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid DateTime."
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Public\Submit-Renewal.ps1:49 char:21

And then:
Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid DateTime."
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.11.0\Public\New-PACertificate.ps1:89 char:9

Both these lines refers to a function 'Get-DateTimeOffsetNow' that i don't see anywhere else.

**Comment by rmbolger** [comment] 2019-12-02 01:33
Hi @Genghes. Thanks for the report. `Get-DateTimeOffsetNow` is a function that exists in Private\MockWrappers.ps1 which is dot sourced when the module is imported. It's a one-line function that wraps `[System.DateTimeOffset]::Now` so I can mock it in tests. But I don't think that's the problem here.

That same line is also attempting to parse the `RenewAfter` property of the order object and appears to be failing which is weird because it is only ever written by the module after getting a new cert successfully. Can you run the following and post the value of `expires`, `CertExpires`, and `RenewAfter` for the order that is failing to renew?

```powershell
Get-PAOrder | Format-List
```

Hypothetically they should all be ISO 8601 formatted date strings with the format `'yyyy-MM-ddTHH:mm:ssZ'`.

**Comment by Genghes** [comment] 2019-12-02 22:19
Hi.
The output from Get-PAOrder | Format-List looks OK.
But if t temporary create the function Get-DateTimeOffsetNow and run it, i get:
DateTime      : 02.12.2019 18.24.19
UtcDateTime   : 02.12.2019 17.24.19
LocalDateTime : 02.12.2019 18.24.19
Date          : 02.12.2019 00.00.00
Day           : 2
DayOfWeek     : Monday
DayOfYear     : 336
Hour          : 18
Millisecond   : 653
Minute        : 24
Month         : 12
Offset        : 01:00:00
Second        : 19
Ticks         : 637109078596531174
UtcTicks      : 637109042596531174
TimeOfDay     : 18:24:19.6531174
Year          : 2019

This is NOT formatted the same?
I'm guessing that's because i have Norwegian Region settings?
But then i tried changing region to English and got:
DateTime      : 12/2/2019 11:16:20 PM
UtcDateTime   : 12/2/2019 10:16:20 PM
LocalDateTime : 12/2/2019 11:16:20 PM
Date          : 12/2/2019 12:00:00 AM
Day           : 2
DayOfWeek     : Monday
DayOfYear     : 336
Hour          : 23
Millisecond   : 666
Minute        : 16
Month         : 12
Offset        : 01:00:00
Second        : 20
Ticks         : 637109253806666620
UtcTicks      : 637109217806666620
TimeOfDay     : 23:16:20.6666620
Year          : 2019

And still same error running Submit-Renewal...

**Comment by Genghes** [comment] 2019-12-02 22:21
Hahaha.. Posted all BUT the output you asked for..

expires           : 2019-12-08T23:53:49Z
CertExpires       : 2020-02-29T22.55.59Z
RenewAfter        : 2020-01-30T22.55.59Z

**Comment by rmbolger** [comment] 2019-12-02 23:35
Yeah, the output of `Get-DateTimeOffsetNow` is just a [DateTimeOffset](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset) object which gets rendered to the console according to your culture settings. The culture shouldn't affect how it's compared to other objects of the same type.

However, the dates you posted from the properties do shed some light on what the problem might be. The `expires` value is returned directly from the ACME server as a string and not subject to any PowerShell related culture formatting. Notice how it has the US style `:` as the separator between hour, minute, second values. The `CertExpires` and `RenewAfter` values on the other hand are originally .NET [DateTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime) objects that are converted to strings using [ToString](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tostring) with a custom format of `yyyy-MM-ddTHH:mm:ssZ`. And despite the fact that the format string uses `:` as separators, it appears to be converting them to `.` for the current culture. What I don't get is why the subsequent `[DateTimeOffset]::Parse()` call doesn't recognize that same culture formatting as a valid date.

In any case, it's clear I need to be more explicit about the culture stuff when formatting and parsing these date values. I'm leaning towards making everything use the US culture to keep things consistent with the other dates returned by the ACME server. Just so I can make sure I reproduce this properly on a test machine, can you post the output of `Get-Culture`?

**Comment by Genghes** [comment] 2019-12-03 00:03
Did a bit more noob debugging.
If i do a Write-Host $order (inserted on line 47 of Submit-Renewal) i get:
 @{status=valid; expires=2019-12-08T23:53:49Z; identifiers=System.Object[]; authorizations=System.Object[]; finalize=https://acme-v02.api.letsencrypt.org/acme/finalize.......

I don't get an object? I think?.
I might just be confusing you here..
I'm a .net guy, not a powershell guy..

**Comment by Genghes** [comment] 2019-12-03 00:08
Get-Culture
This is after trying to change region to English:
Get-Culture:
LCID             Name             DisplayName                                                                                                                            
----             ----             -----------                                                                                                                            
1033             en-US            English (United States)

**Comment by rmbolger** [comment] 2019-12-03 00:16
Generally, you'd want to use `Write-Verbose` rather than `Write-Host` because the latter has a tendency to add things to the PowerShell pipeline that can interfere with other returned objects the code would be expecting. The output you saw is PowerShell's attempt to convert the order object ([PSCustomObject](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.pscustomobject) with a custom type name) to a string for console output. 

For the culture, I was hoping to get the output prior to changing to US culture. 

Though if you need a quick fix, changing to US culture and then creating a new order from scratch (rather than trying to renew) should hypothetically fix things for as long as it stays US culture.

**Comment by Genghes** [comment] 2019-12-03 00:23
Before changing:
LCID             Name             DisplayName                                                                                                                                                                            
----             ----             -----------                                                                                                                                                                            
1044             nb-NO            Norwegian, Bokmål (Norway)

**Comment by rmbolger** [comment] 2019-12-03 00:50
Thanks. Just for completeness, can I get the output of `$PSVersionTable` and if you're not using PowerShell Core also `(Get-ItemProperty "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full").Release`?

**Comment by Genghes** [comment] 2019-12-03 00:51
Version:
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.14393.3053                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.14393.3053                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1

**Comment by Genghes** [comment] 2019-12-03 00:52
NET.release:
528049

**Comment by rmbolger** [comment] 2019-12-03 01:47
Ok, pushed a fix to dev/master that should prevent the problem for newly created orders. Any old orders that have "bad" values for `RenewAfter` or `CertExpires` will still cause problems. So you'll probably want to delete them and re-create them from scratch.

Let me know how that works for you.

**Comment by Genghes** [comment] 2019-12-03 23:30
Reverted back to Norwegian culture, and issued a new cert. Now renewal works fine.
Thank you for the fix.

**Comment by rmbolger** [comment] 2019-12-10 23:46
The fix is now live with the 3.12.0 release.

**Closed by rmbolger** 2019-12-10 23:46 UTC
Labels: bug
