### ISSUE TITLE
DeSEC fails due to API throttling when using many domains

### ISSUE THREAD

**Issue by MatthiasLanter** [rmbolger/Posh-ACME#272] opened 2020-08-11 14:59 UTC
First, thank you for the great work!

I got the following error for a requested certificate including 6 domains:

Invoke-RestMethod : {"detail":"Request was throttled. Expected available in 1 second."}
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.15.1\DnsPlugins\DeSEC.ps1:216 char:18
+         $rrset = Invoke-RestMethod $recordUri -Headers $auth `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

As a quick workaround I added a Start-Sleep -s 3 before.

Because there is no try - catch - retry in PowerShell to handle that error in a better way, maybe a throttling parameter could be a fix.

Addition: I get the same error with New-PACertificate.

thanks in advance

**Comment by rmbolger** [comment] 2020-08-12 04:53
Thanks for the report, @MatthiasLanter!

I can't seem to find any details in DeSEC's [documentation](https://desec.readthedocs.io/en/latest/quickstart.html) about API rate limits. But I found some references in their [site's source](https://github.com/desec-io/desec-stack/blob/115b147a22fd6fff3998666fb92da9360c278d66/api/api/settings.py#L115-L123). While I could probably add a simple tracking variable to make sure we don't sent a request more often than once every 2 seconds or so...it might end up being more robuts to catch the error and back off as appropriate. Let me try to reproduce the throttling and see what I can come up with.

**Comment by rmbolger** [comment] 2020-08-13 05:35
Hey @MatthiasLanter. It turns out deSEC throws a nice HTTP 429 response code with a `Retry-After` header that made rather easy to know when to back off and for how long. I just committed a fix to the dev/master branch. Give it a try and see if it works for you.

**Comment by MatthiasLanter** [comment] 2020-08-13 10:28
Hey @rmbolger

Thanks for the quick fix! The first tests are promising. But, because I renewed all certificates two days ago with my workaround, it's not quite the same procedure now.

**Comment by rmbolger** [comment] 2020-08-14 04:33
I'm gonna close the issue for now. Feel free to re-open if it crops back up.

**Closed by rmbolger** 2020-08-14 04:33 UTC
Labels: bug
